"""FSC catalog loader. The catalog JSON is generated by scripts/parse_fsc_pdf.py."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True, slots=True)
class FscEntry:
    code: str  # 4 digits, e.g. "3408"
    title: str


class FSCCatalog:
    def __init__(self, entries: list[FscEntry]) -> None:
        self._entries = entries
        self._by_code = {e.code: e for e in entries}

    @classmethod
    def load(cls, path: str | Path) -> "FSCCatalog":
        data = json.loads(Path(path).read_text(encoding="utf-8"))
        entries = [FscEntry(code=row["code"], title=row["title"]) for row in data]
        return cls(entries)

    def lookup(self, code: str) -> FscEntry | None:
        return self._by_code.get(code)

    def list_all(self) -> list[FscEntry]:
        return list(self._entries)

    def __len__(self) -> int:
        return len(self._entries)

    def __contains__(self, code: object) -> bool:
        return isinstance(code, str) and code in self._by_code
